/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteRouteImport } from './routes/sign-up/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardSettingsRouteRouteImport } from './routes/(dashboard)/settings/route'
import { Route as dashboardProfileRouteRouteImport } from './routes/(dashboard)/profile/route'
import { Route as dashboardProjectsIndexRouteImport } from './routes/(dashboard)/projects/index'
import { Route as dashboardProjectsProjectIdRouteImport } from './routes/(dashboard)/projects/$projectId'

const SignUpRouteRoute = SignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardSettingsRouteRoute = dashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardProfileRouteRoute = dashboardProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardProjectsIndexRoute = dashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardProjectsProjectIdRoute =
  dashboardProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/profile': typeof dashboardProfileRouteRoute
  '/settings': typeof dashboardSettingsRouteRoute
  '/': typeof dashboardIndexRoute
  '/projects/$projectId': typeof dashboardProjectsProjectIdRoute
  '/projects': typeof dashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/profile': typeof dashboardProfileRouteRoute
  '/settings': typeof dashboardSettingsRouteRoute
  '/': typeof dashboardIndexRoute
  '/projects/$projectId': typeof dashboardProjectsProjectIdRoute
  '/projects': typeof dashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/(dashboard)/profile': typeof dashboardProfileRouteRoute
  '/(dashboard)/settings': typeof dashboardSettingsRouteRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/projects/$projectId': typeof dashboardProjectsProjectIdRoute
  '/(dashboard)/projects/': typeof dashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/sign-up'
    | '/profile'
    | '/settings'
    | '/'
    | '/projects/$projectId'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sign-up'
    | '/profile'
    | '/settings'
    | '/'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/login'
    | '/sign-up'
    | '/(dashboard)/profile'
    | '/(dashboard)/settings'
    | '/(dashboard)/'
    | '/(dashboard)/projects/$projectId'
    | '/(dashboard)/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  SignUpRouteRoute: typeof SignUpRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/profile': {
      id: '/(dashboard)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof dashboardProfileRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/projects/': {
      id: '/(dashboard)/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof dashboardProjectsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/projects/$projectId': {
      id: '/(dashboard)/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof dashboardProjectsProjectIdRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardProfileRouteRoute: typeof dashboardProfileRouteRoute
  dashboardSettingsRouteRoute: typeof dashboardSettingsRouteRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardProjectsProjectIdRoute: typeof dashboardProjectsProjectIdRoute
  dashboardProjectsIndexRoute: typeof dashboardProjectsIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardProfileRouteRoute: dashboardProfileRouteRoute,
  dashboardSettingsRouteRoute: dashboardSettingsRouteRoute,
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardProjectsProjectIdRoute: dashboardProjectsProjectIdRoute,
  dashboardProjectsIndexRoute: dashboardProjectsIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  SignUpRouteRoute: SignUpRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
